# Generated by Django 6.1.1 on 2026-09-29 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Región')),
                ('zona', models.CharField(max_length=50, verbose_name='Zona Geográfica (Ej: Norte Chico)')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Ciudad o Destino')),
                ('descripcion', models.TextField(verbose_name='Descripción Turística')),
                ('imagen', models.CharField(help_text='Ej: serena.jpg o vallenar.jpg', max_length=100, verbose_name='Archivo de Imagen')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='destinos.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
            },
        ),
    ]
