# Generated by Django 6.1.1 on 2026-09-29 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Paquete')),
                ('noches', models.PositiveIntegerField(verbose_name='Cantidad de Noches')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio ($ CLP)')),
                ('incluye', models.TextField(verbose_name='Servicios Incluidos')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='destinos.destino', verbose_name='Destino Asociado')),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
            },
        ),
    ]
